// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onfvfkxpvvpygxhzhxyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uZnZma3hwdnZweWd4aHpoeHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODYwODMsImV4cCI6MjA2ODE2MjA4M30.XIzV4wYIF2JK6efqiuHQiUMZ0LeY5dBVfGUM_qoU1sI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});